
name: GitHub Pages

on:
  push:
    branches:
      - 'devel'
    # paths:
    #   - 'src/**/*'
    #   - 'example/**/*'

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        nim: [ '1.6.2' ]
    name: Nim ${{ matrix.nim }} sample
    steps:
      - uses: actions/checkout@v2
      - name: Setup nim
        uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: ${{ matrix.nim }}
      - name: Install dependencies
        run: |
          nimble install -d -Y
      - name: Insall web_preprocessor dependencies
        run: brew install libsass mozjpeg
      - name: Build
        run: nimble build
      - name: Build site
        run: |
          ./crown_ui build --cwd ./example
          nimble buildAssets
      - name: Deploy
        if: matrix.nim == '1.6.2'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./example/build
          cname: crown_ui.bungos.me
          publish_branch: ghpages # since not use Jekyll choose another branch