
name: GitHub Pages

on:
  push:
    branches:
      - 'devel'
    # paths:
    #   - 'src/**/*'
    #   - 'example/**/*'

jobs:
  deploy-pages:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - nim-version: 'devel --latest'
            cache-key: 'devel-latest'
    steps:
      - uses: actions/checkout@v2
      - name: Get Date
        id: get-date
        run: echo "::set-output name=date::$(date "+%Y-%m-%d")"
        shell: bash

      - name: Cache choosenim
        id: cache-choosenim
        uses: actions/cache@v1
        with:
          path: ~/.choosenim
          key: ${{ runner.os }}-choosenim-${{ matrix.cache-key }}-${{ steps.get-date.outputs.date }}
      - name: Cache nimble
        id: cache-nimble
        uses: actions/cache@v1
        with:
          path: ~/.nimble
          key: ${{ runner.os }}-nimble-${{ hashFiles('*.nimble') }}

      - name: Install Nim
        uses: jiro4989/setup-nim-action@v1
        with:
           nim-version: ${{ matrix.nim_version }}
      - name: Install dependencies
        run: nimble install -d -Y
      - name: Build
        run: nimble build
      - name: Build site
        run: |
          ./crown_ui --cwd ./example
          nimble buildStatic
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./example/build
          publish_branch: ghpages # since not use Jekyll choose another branch