
name: GitHub Pages

on:
  push:
    branches:
      - 'devel'
    # paths:
    #   - 'src/**/*'
    #   - 'example/**/*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nim: [ '1.4.6', 'stable', 'devel' ]
    name: Nim ${{ matrix.nim }} sample
    steps:
      - uses: actions/checkout@v2
      - name: Setup nim
        uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: ${{ matrix.nim }}
      - name: Install dependencies
        run: |
          nimble install -d -Y
      - name: Build
        run: nimble build
      - name: Build site
        run: |
          ./crown_ui --cwd ./example
          nimble buildStatic
      - name: Deploy
        if: matrix.nim == '1.4.6'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./example/build
          publish_branch: ghpages # since not use Jekyll choose another branch